services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: msvc_users
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=root123
      - POSTGRES_DATABASE=msvc_courses
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-users:
    container_name: msvc-users
    image: users:latest
    ports:
      - "8001:8001"
    env_file:
      - ./msvc-users/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
  msvc-courses:
    container_name: msvc-courses
    image: courses:latest
    ports:
      - "8002:8002"
    env_file:
      - ./msvc-courses/.env
    networks:
      - spring
    depends_on:
      - postgres14
    restart: always

volumes:
  data-mysql:
    name: data-mysql
    external: true
  data-postgres:
    name: data-postgres
    external: true
networks:
  spring:
    name: spring
